### ISSUE TITLE
ロゴ画像変更

### ISSUE THREAD

**Issue by keitasuzukijp** [covid19-yamanashi/covid19#1]
- 山梨県公式ではないため独自のロゴ？
- 場所: /logo.svg

**Comment by keitasuzukijp** [comment]
仮に作成。
developmentにpush済み

**Comment by keitasuzukijp** [comment]
ロゴ作ってくれる人募集中ー！

**Comment by keitasuzukijp** [comment]
@esmz さん
先ほどはありがとうございます。ロゴよろしくお願いいたします！

・コロナっぽいアイコン（色は #694e84 / #cbbbdf / #ede9f7 あたり）
・その右側に下記の文字
　STOP COVID-19
　YAMANASHI
・画像はsvg形式で static/logo.svg を上書き

参考：
https://stopcovid19.hokkaido.dev/
https://stopcovid19.code4.nagoya/

**Comment by keitasuzukijp** [comment]
@esmz ロゴの件、清水さんが作業できる現実的な線でスケジュール1回切りましょうか？

**Comment by esmz** [comment]
@keitasuzukijp 
今進めているので後ほどプルリクできればと思います！

**Comment by esmz** [comment]
@keitasuzukijp 
プルリクしちゃいましたが・・
すみません、こんな感じでどうですか？

![logo](https://user-images.githubusercontent.com/22608977/76635074-3ce8bf80-658a-11ea-815d-c9e8fcbaf4cf.jpg)

**Comment by keitasuzukijp** [comment]
@esmz 突然にもかかわらずありがとうございました！
