### ISSUE TITLE
公開作業

### ISSUE THREAD

**Issue by keitasuzukijp** [covid19-yamanashi/covid19#18]
#1 #7 #10 #13 が完了したら公開しちゃいましょうか。
@yuukis 公開時にどのような作業が必要でしょうか。yuukisさん以外にも助っ人が必要ですか？

**Comment by yuukis** [comment]
@keitasuzukijp 
`development` を `master` にマージしたら、自動適に本番用の netlify にデプロイされるようにしたいなーと思ってます。  
設定します！

**Comment by keitasuzukijp** [comment]
@yuukis 公開前のIssueを完了しました。この土日にもしお時間があれば本番への反映をお願いいたします。

**Comment by yuukis** [comment]
@keitasuzukijp 公開しました！
https://stopcovid19.yamanashi.dev/

> development を master にマージしたら、自動的に本番用の netlify にデプロイされる

上記の仕掛けを設定済みですー
