### ISSUE TITLE
データのスクレイピングの復旧（またはオープンデータの利用？）

### ISSUE THREAD

**Issue by keitasuzukijp** [covid19-yamanashi/covid19#184]
## 改善詳細 / Details of Improvement
- 山梨県公式サイトの仕様変更によりデータのスクレイピングができなくなり、陽性患者数などのデータが自動更新されなくなってしまている。

## 期待する見せ方・挙動 / Expected behavior
- データ（陽性患者数／陽性患者の属性／県内の疑似症例の検査状況／帰国者・接触者相談センター相談件数／新型コロナウイルス感染症専用相談ダイヤル相談件数）の自動更新を復旧させたいです。

## 参考
- @daisuke19891023 さんによるメンテ用レポジトリ https://github.com/daisuke19891023/covid19-yamanashi-scraping
- オープンデータ化されているという情報 https://github.com/daisuke19891023/covid19-yamanashi-scraping/issues/77

**Comment by keitasuzukijp** [comment]
@daisuke19891023 @yuukis 
一応Issueをたてさせていただきました。
もし解決策がありましたら、お手数をおかけしますがよろしくお願いいたします…。

**Comment by daisuke19891023** [comment]
@keitasuzukijp  @yuukis 
今エラーになっている原因は、GitHubActionsの仕様変更により、更新後のdata.jsonをmasterに反映させる処理が失敗していることが原因のようです。

コマンドの作成者によると、create-pull-requestのバージョンを`v3`に上げればよいとのコメントがありましたので、更新してpull requestを投げさせていただきます
https://github.com/peter-evans/create-pull-request/issues/632

**Comment by daisuke19891023** [comment]
スクレイピングのrepositoryにてdata.jsonの生成元をオープンデータのExcelに変更しました。
データの並び順などに変更はありませんが、Excelとサイトのhtmlとで居住地の表記が一部変更されている箇所があるので、もしかしたらGitHubActionによるデータ更新時にconflictが発生するかもしれません。恐れ入りますが、mergeに失敗した際はdata.jsonを新しい方に更新する作業をお願いします

**Comment by daisuke19891023** [comment]
問題なくマージされたらIssueを再度closeします

**Comment by yuukis** [comment]
> mergeに失敗した際はdata.jsonを新しい方に更新する作業をお願いします

上記、承知しました！

**Comment by keitasuzukijp** [comment]
@yuukis 
こちら、現在 yuukis さんが手作業で更新されているということで（汗）
何かよい解決策はありますでしょうか…。
取り急ぎ更新を担当しましょうか？

**Comment by daisuke19891023** [comment]
データ更新を反映させる以下のPullRequest（スクレイピングBotから自動生成されてます）がConflict状態のまま放置されているので、こちらをResolveしてMergeしていただければと思います
※日々更新内容はBotから送られてきていますが、その内容が反映されていない状態になっております

https://github.com/covid19-yamanashi/covid19/pull/232

**Comment by yuukis** [comment]
コメントありがとうございます。
PullRequest が飛んできているのは承知しているのですが、
内容が以下の通りであるためマージが出来ていない状況です。（お伝えできていませんでした。すみません）

・lastUpdate 2021/01/03 00:07 になっている
・県内528例目 以降のデータが無い
・2020-12-28 以降の陽性患者数が反映されていない

# あと出典元である県サイトのオープンデータのファイル名も、日によって変わったりするので困りますね。。
# ・yousei.xls
# ・0616yousei.xlsx

**Comment by daisuke19891023** [comment]
@yuukis 

> ・lastUpdate 2021/01/03 00:07 になっている
> ・県内528例目 以降のデータが無い
> ・2020-12-28 以降の陽性患者数が反映されていない
⇒最新のデータでは上記観点はすべて解消されているので、https://github.com/covid19-yamanashi/covid19/tree/create-pull-request/patchのブランチを一度削除すれば、最新のデータがプルリクエストされるようになると思います。

**Comment by yuukis** [comment]
@daisuke19891023  
> https://github.com/covid19-yamanashi/covid19/tree/create-pull-request/patch
> のブランチを一度削除すれば、最新のデータがプルリクエストされるようになると思います。ブランチの削除は可能ですか？

リモートリポジトリ上の上記ブランチを 20日に削除しましたが、その後 PR されたデータは状況変わっていないようです。。

#235

**Comment by daisuke19891023** [comment]
すみません、原因分かりました。
データを取ってくる際、スクレイピングリポジトリのブランチをmainに変えなければいけないところ、masterブランチを参照するコードになっておりました。
※数ヶ月前にメインのブランチ名をGitHubの規約によりmainに変更していました。

workflowのyamlファイルの修正が必要になりますので、このあと、修正してPull Requestを出させていただきます

**Comment by daisuke19891023** [comment]
遅くなりましたが修正のpull reuestを投げさせていただきました。ご確認お願いします
