### ISSUE TITLE
2021.2.20からデータ更新されていない?

### ISSUE THREAD

**Issue by paichi81** [covid19-yamanashi/covid19#233]
## 起こっている問題 / The Problem
- 県公式情報をみると3月にはいって陽性者がでている
- 最終更新が2/20までとなっている

## 期待する見せ方・挙動 / Expected Behavior
- 最新状況に更新する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by yuukis** [comment]
ご指摘ありがとうございます！
本日公開されている最新データに更新しましたのでクローズします。
