### ISSUE TITLE
サイト内情報について

### ISSUE THREAD

**Issue by kokotomittten** [covid19-yamanashi/covid19#234]
サイト内「お子様をお持ちの皆様へ」内の相談の目安「37.5℃以上の発熱が４日以上」といったもの等が、厚生労働省のほうで昨年修正されております。確認とご修正願えませんでしょうか。ご検討宜しくお願い致します。※「コロナ 相談 目安 変更 37.5」で検索

**Comment by keitasuzukijp** [comment]
@kokotomittten 
こちら確認が大変遅くなりました。
この後下記のように変更いたします。

感染症を疑う場合の対応
〇 息苦しさ（呼吸困難）、強いだるさ（倦怠感）、高熱等の強い症状がある場合、または発熱や咳などの比較的軽い風邪の症状が続いている場合は、各窓口にご相談ください。<br />各窓口の電話番号等については「新型コロナウイルス感染症に関する相談窓口等」（山梨県）をご確認ください。「新型コロナウイルス感染症に関する相談窓口等」（山梨県）

**Comment by yuukis** [comment]
本番サイトに反映済み。close します。
https://stopcovid19.yamanashi.dev/parent/
