### ISSUE TITLE
「宿泊事業者の皆さまへ」ページ作成

### ISSUE THREAD

**Issue by keitasuzukijp** [covid19-yamanashi/covid19#24]
# 改善詳細 / Details of Improvement
岐阜県のように県内の宿泊事業者向けページを新設するのはどうでしょうか。

# 期待する見せ方・挙動 / Expected behavior

## 見せ方

- 岐阜県と同様にページ作成 https://covid19-gifu.netlify.com/lodging
- サイドメニュー「企業の皆様・はたらく皆様へ」の下にメニュー追加。アイコン欲しい。

### ページタイトル: 
宿泊事業者の皆さまへ
### ページ内容
宿泊施設における新型コロナウイルス感染症への対応について
山梨県内の宿泊施設における新型コロナウイルス感染症への対応については下記をご覧ください。
https://www.pref.yamanashi.jp/eisei-ykm/20200212ryokan_corona.html

笛吹市：宿泊料金割引事業
笛吹市では令和2年4月1日より市内の旅館・ホテルの宿泊料金の割引事業を実施します。
https://www.city.fuefuki.yamanashi.jp/kanko/sangyo/kanko/waribikijigyou.html

**Comment by keitasuzukijp** [comment]
これやってみます。

**Comment by keitasuzukijp** [comment]
どなたか
こちら内容の作成は取り急ぎ行ったのですが、
サイドメニューへのicon表示の方法がわかりません。
どなたか解決方法がわかりますでしょうか？

●対象ファイル
components/SideNavigation.vue

●状況
 メニューにアイコンを表示したいが出し方不明

●望む表示
サイドメニュー「宿泊事業者の皆さまへ」の左側に
岐阜と同じアイコン出したい。
https://covid19-gifu.netlify.com/
https://github.com/CODE-for-GIFU/covid19/blob/develop/pages/lodging.vue

**Comment by keitasuzukijp** [comment]
鈴木が行った作業
https://github.com/covid19-yamanashi/covid19/commit/3aff90b395908f1ded1088bf6afb5719802c90d4

**Comment by yuukis** [comment]
こちら、新規ブランチを切り出しました！
[feature/issue-24-lodging](https://github.com/covid19-yamanashi/covid19/tree/feature/issue-24-lodging) ブランチです。
