### ISSUE TITLE
「新型コロナウイルス感染症が心配なときに」ページを復活

### ISSUE THREAD

**Issue by keitasuzukijp** [covid19-yamanashi/covid19#25]
# 改善詳細 / Details of Improvement

- 公開時には削除した「新型コロナウイルス感染症が心配なときに」ページ、わかりやすいので掲載したほうがよいのではないか。
東京都（オリジナル）
https://stopcovid19.metro.tokyo.lg.jp/flow
神奈川県版
https://www.pref.kanagawa.jp/osirase/1369/flow

# 期待する見せ方・挙動 / Expected behavior

## 見せ方

- 山梨版に色を変える（#694e84）
- 各相談窓口を変更する（下記参照）
- サイドバー「県内の最新感染動向」の下にメニュー追加。

## 変更箇所（番号はスクリーンショット参照）

1）テキスト及びリンク先変更：
●「各保健所の電話番号は福祉保健局HPへ」を変更：「こちらから管轄地域の保健所へご連絡ください」
●リンク先: https://www.pref.yamanashi.jp/koucho/coronavirus/info_coronavirus.html#soudanmadoguchi

2）テキスト変更
●新型コロナコールセンター」を変更：「新型コロナウイルス感染症専用相談ダイヤル」
●電話番号を変更：055-223-8896

3）そのママ

4）テキスト変更
「東京都健康安全研究センター等」を変更：「感染症指定医療機関等」

5）テキスト及びリンク先変更
●テキスト: 詳細を見る（山梨県のウェブサイト）
●リンク先: https://www.pref.yamanashi.jp/koucho/coronavirus/info_coronavirus.html#soudanmadoguchi

# スクリーンショット / Screenshot
![新型コロナウイルス感染症が心配なときに](https://user-images.githubusercontent.com/9653448/76677718-0f952380-6615-11ea-96ab-de3d60b8c6c4.png)

**Comment by keitasuzukijp** [comment]
場所は /page/flow.vue です。
ひとまず東京サイトから最新版をコピペしてファイルを復活させました。

**Comment by yuukis** [comment]
ひとまず削除したページを復活させました！
[feature/issue-25-flow](https://github.com/covid19-yamanashi/covid19/tree/feature/issue-25-flow) ブランチで復活してあります。

**Comment by yuukis** [comment]
これ、ちょっとやってみますね！

**Comment by yuukis** [comment]
とりあえず山梨版カラーにはしてみた

![FireShot Capture 020 - 新型コロナウイルス感染症が心配なときに - 山梨県 新型コロナウイルス感染症対策サイト - localhost](https://user-images.githubusercontent.com/2931035/76844028-0fe52700-6880-11ea-89eb-551e1fd5bb3f.png)

**Comment by yuukis** [comment]
テキストもひととおり差し替えてみました
![FireShot Capture 022 - 新型コロナウイルス感染症が心配なときに - 山梨県 新型コロナウイルス感染症対策サイト - localhost](https://user-images.githubusercontent.com/2931035/76850355-8f77f380-688a-11ea-8bca-8f0a774edecc.png)

**Comment by yuukis** [comment]
ただ、モバイルで見たときに修正が反映されていない。。おかしいぞ
と思ったら、これ画像じゃん。PNGじゃん。

ということで、どなたかモバイル用の PNG 画像作成をお願いしたいです！
ファイルの場所は [static/flow/sp](https://github.com/covid19-yamanashi/covid19/tree/feature/issue-25-flow/static/flow/sp) です

![localhost_3000_flow_(Galaxy S5)](https://user-images.githubusercontent.com/2931035/76850693-41afbb00-688b-11ea-897e-850e22d1f983.png)

**Comment by esmz** [comment]
@yuukis こちら画像作成、対応いたしますね!

**Comment by esmz** [comment]
プッシュいたしましたのでご確認お願いいたしますm(_ _)m

**Comment by yuukis** [comment]
@esmz ありがとうございます！確認しました。
あとは画像内のテキストを、以下の通りPCと合わせられれば完了かなと思います。
可能であればお願いしたいです！

[sp_flow_04@2x.png](https://github.com/covid19-yamanashi/covid19/tree/305cbcb124b4e1faedaa4fb92f67091e051e6e76/static/flow/sp/sp_flow_04@2x.png)
→「新型コロナコールセンター」を変更：「新型コロナウイルス感染症専用相談ダイヤル」

[sp_flow_06_02@2x.png](https://github.com/covid19-yamanashi/covid19/tree/305cbcb124b4e1faedaa4fb92f67091e051e6e76/static/flow/sp/sp_flow_06_02@2x.png)
→「東京都健康安全研究センター等」を変更：「感染症指定医療機関等」

[sp_flow_tel_01@2x.png](https://github.com/covid19-yamanashi/covid19/tree/305cbcb124b4e1faedaa4fb92f67091e051e6e76/static/flow/sp/sp_flow_tel_01@2x.png)
→電話番号を変更：055-223-8896

**Comment by keitasuzukijp** [comment]
🙇‍♂️

**Comment by esmz** [comment]
@yuukis 細かくご教示頂いて助かります🙇‍♂
追加分再度プッシュいたしました！

**Comment by yuukis** [comment]
@esmz 確認しました！ありがとうございまーす😂
これで PR 出します

![localhost_3000_cities(iPhone 6_7_8)](https://user-images.githubusercontent.com/2931035/77137720-62a62500-6ab2-11ea-9415-c48fc584ccc7.png)
