### ISSUE TITLE
「経済変動対策融資（不況業種対策関係）」がリンク切れしている

### ISSUE THREAD

**Issue by yuukis** [covid19-yamanashi/covid19#27]
## 起こっている問題 / The Problem
- 「[企業の皆様・はたらく皆様へ](https://stopcovid19.yamanashi.dev/worker)」ページの「経済変動対策融資（不況業種対策関係）」のリンク先が切れている

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by keitasuzukijp** [comment]
@yuukis 
ありがとうございます。
情報アップデートしステージングに上げました。 126fe1e

**Comment by yuukis** [comment]
確認しました。問題ありません！
master に反映しましたのでクローズします。
