### ISSUE TITLE
data.json の自動更新

### ISSUE THREAD

**Issue by yuukis** [covid19-yamanashi/covid19#28]
## 改善詳細 / Details of Improvement
- 陽性患者数や検査状況等を更新する際、現状は [data.json ](https://github.com/covid19-yamanashi/covid19/blob/development/data/data.json)を手動で更新する必要がある
- 手動で更新する場合、情報を誤って転記してしまう恐れがある

## 期待する見せ方・挙動 / Expected behavior
- [出典元ページ](https://www.pref.yamanashi.jp/koucho/coronavirus/info_coronavirus.html)からスクレイピングして自動生成できると良い
- スクレイピングが難しい場合は、グラフ用の[スプレッドシート](https://docs.google.com/spreadsheets/d/1CQpkwcMZRJHD27wTESbnP0Yj1WxwUMnUOW-EF0XvkAw/edit?usp=sharing)から data.json を自動生成する

**Comment by daisuke19891023** [comment]
現在pythonによるスクレイピングツールを作っているのですが、data.jsonの項目で一点確認させてください。
個別の患者さんの退院情報は出展元のページのどこから取得できますか？

**Comment by yuukis** [comment]
@keitasuzukijp さん、患者さん個別の退院情報の出典元はご存知ですか？
もし出典元が無ければ、「陽性患者の属性」から「退院」は削除した方が良いかなと思っています。

**Comment by yuukis** [comment]
@daisuke19891023 
個別の患者さんの退院情報は県からは発表しない意向のようですので、
data.json では退院は `null` としていただければと思います。

**Comment by daisuke19891023** [comment]
承知しました。

**Comment by daisuke19891023** [comment]
日時で県のホームページからデータを取得し、差分があった場合はdata.jsonを更新してpull requestを出す形にしたいと思います

**Comment by yuukis** [comment]
> 日時で県のホームページからデータを取得し、差分があった場合はdata.jsonを更新してpull requestを出す形にしたいと思います

ありがとうございます！助かります！！

**Comment by daisuke19891023** [comment]
@yuukis 

`data.json`を更新し、pull requestを作成するためのymlを作成しました。
内容はpull requestのコメントに記述しました。

スクレイピング自体は以下のrepositoryで行っています。
https://github.com/daisuke19891023/covid19-yamanashi-scraping

作成にあたり、[こちらの記事](https://qiita.com/wataruoguchi/items/0f69f72777237674074b#comments)を参考にしました。

もしかしたら受信側のrepositoryの管理者権限が必要になるかもしれませんが、その際は改めて相談させてください。

**Comment by daisuke19891023** [comment]
@yuukis 
@keitasuzukijp 

マージしていただきありがとうございます。
data.jsonの更新イベントを実行したのですが、権限の関係でこちらのrepositoryでイベントを受けることが出来ませんでした。
当repositoryでdispatch eventを受けるためにはrepositoryのAdmin権限が必要らしいのですが、私に権限を付与していただくことは可能ですか？

[長野県版 新型コロナウイルス感染症対策サイト データ更新を自動化した話](https://qiita.com/wataruoguchi/items/0f69f72777237674074b)

**Comment by daisuke19891023** [comment]
@yuukis 
対応いただきありがとうございました！無事イベントを受信し、pull requestが作成されることが確認できました！

**Comment by yuukis** [comment]
@daisuke19891023 

>対応いただきありがとうございました！無事イベントを受信し、pull requestが作成されることが確認できました！

よかったです！ご確認いただきありがとうございます。
結果的にAdmin権限は付与していないのですが、チームに招待したことで Write権限が付与され、対応出来たようです。

下記ページを参考にしました。
https://github.community/t5/GitHub-Actions/repository-dispatch-response-unpredictable/td-p/44018#

今後ともよろしくお願いします！！
