### ISSUE TITLE
authorについて

### ISSUE THREAD

**Issue by soma-tanaka** [covid19-yamanashi/covid19#32]
## 起こっている問題 / The Problem
- meta タグの author が東京都のままなので、変更したい

## 期待する見せ方・挙動 / Expected Behavior
- 現状の下記ソースを正しい内容に修正  
<meta data-n-head="ssr" data-hid="author" name="author" content="東京都">

## 修正内容、修正箇所について
- 修正内容について
当サイトのauthorについて、「stopcovid19.yamanashi.devチーム」「stopcovid19.yamanashi.dev」など、内容を検討したい

- 修正箇所について  
nuxt.config.ts に下記追記でローカル上は動作しましたが、ご確認いただければ幸いです。
`      {
        hid: 'author',
        name: 'author',
        content:
          'stopcovid19.yamanashi.dev'
      },`

**Comment by keitasuzukijp** [comment]
どなたかお時間ある際によろしくお願いいたします！
