### ISSUE TITLE
グラフに「電話相談窓口の相談件数」を追加する

### ISSUE THREAD

**Issue by yuukis** [covid19-yamanashi/covid19#35]
## 改善詳細 / Details of Improvement
- [県のサイト](https://www.pref.yamanashi.jp/koucho/coronavirus/info_coronavirus.html)に「電話相談窓口の相談件数」が掲載されているので、陽性患者数と同様にトップページでグラフ表示させても良さそう
- 載せるグラフは「帰国者・接触者相談センター」、「新型コロナウイルス感染症専用相談ダイヤル」の2つ

**Comment by keitasuzukijp** [comment]
これ載せたいですね！

**Comment by yuukis** [comment]
これやってみますー
