### ISSUE TITLE
最新のお知らせがリンク切れしている

### ISSUE THREAD

**Issue by yuukis** [covid19-yamanashi/covid19#39]
## 起こっている問題 / The Problem
- 最新のお知らせがリンク切れしている
  - 2020/04/02 新型コロナウイルス感染症患者の発生について（県内9例目） 
  - 2020/04/01 新型コロナウイルス感染症患者の発生について（県内8例目） 
  - 2020/04/01 新型コロナウイルス感染症患者の発生について（県内7例目） 
  - 2020/04/01 新型コロナウイルス感染症患者の発生について（県内6例目） 
- 県で新しい情報が出る度に URL が変わっている

## 期待する見せ方・挙動 / Expected Behavior
- リンクを直す
- 日付も変更する?
  - 情報が更新された日にするか
  - その場合、最新のお知らせの並び順も変更するのか
- もしくは最新のお知らせには載せず、「県内の発生状況」へのリンクを貼るだけにするか
  - https://www.pref.yamanashi.jp/koucho/coronavirus/info_coronavirus.html#hasseijoukyou

**Comment by yuukis** [comment]
@keitasuzukijp 本件、方針どうしましょう？？

**Comment by keitasuzukijp** [comment]
@yuukis 今気づきました！PDFが更新されるたびにファイル名変えてるみたいなので、PDFではなくページにリンク貼るよう修正します。

**Comment by yuukis** [comment]
fb5d1f6082170348fdd497ced03e19c806bdaa07 で対応いただいたことを確認
close します
