### ISSUE TITLE
ページ作成: お子様をお持ちの皆様へ

### ISSUE THREAD

**Issue by keitasuzukijp** [covid19-yamanashi/covid19#4]
以下、原稿です。

> ページタイトル: 
> 臨時休校中の新型コロナウイルス感染症対応についてのお願い

> 1 感染予防・健康管理
> 〇　不特定多数の人の集まる場所等への外出を避け、基本的に自宅で過ごしてください。
> 〇　手洗い、咳エチケット等により、感染予防に努めてください。
> 　（参考）正しい手の洗い方（PDF：357KB）
> https://www.pref.yamanashi.jp/koucho/coronavirus/documents/tadasiitearai_1.pdf
> 〇　規則正しい生活を心がけ、日常の健康管理に十分気を付けてください。
> 　新型コロナウイルスを防ぐには（PDF：250KB）
> https://www.pref.yamanashi.jp/koucho/coronavirus/documents/20200306newcoronabousi.pdf

> 2 感染症を疑う場合の対応
> 〇　風邪の症状や、37.5度以上の発熱が４日以上続いている、強いだるさ（倦怠感）、息苦しさ（呼吸困難）がある場合は、各保健所にご相談ください。
> 〇 型コロナウイルス感染症専用相談ダイヤル
> https://www.pref.yamanashi.jp/koucho/coronavirus/documents/20200306newcoronasentoutelfax.pdf

> 3 学校の臨時休校について
> https://www.pref.yamanashi.jp/kokusai/info_coronavirus/rinjikyuukou.html
> 各市町村ごとの対応状況、学童保育実施についてお知らせしているページです。

> 4 子育て家庭休業助成金制度
> https://www.pref.yamanashi.jp/koucho/coronavirus/info_coronavirus.html#josei
> 子どもが小学校や保育所等へ登校・登園をしなかったことに伴い保護者が休業を余儀なくされた方に、一定額の助成を行うものです。

> 5 その他
> 〇 詳細は、各学校からのお知らせ等をご確認ください。

**Comment by yuukis** [comment]
b102c4b237b1600a3186844c04716aebd72407e4 で反映されていることを確認

<img width="1441" alt="スクリーンショット 2020-03-12 06 34 13" src="https://user-images.githubusercontent.com/2931035/76467210-6e4b7900-642c-11ea-80b0-3a516576c357.png">
