### ISSUE TITLE
県内の最新感染動向（グラフ）データ流し込み

### ISSUE THREAD

**Issue by keitasuzukijp** [covid19-yamanashi/covid19#6]
データ種類洗い出し：鈴木担当

@yuukis 
取り急ぎ初回分としてデータが確実にあるのは下記の3種類になります。
データ自体はこのあと投稿します。

陽性患者数
・合計人数
・棒グラフ（3/1〜本日までの日割り）
・出展: 山梨県ウェブサイト（リンク: https://www.pref.yamanashi.jp/koucho/coronavirus/info_coronavirus.html）

陽性患者の属性
・合計人数
・表
・項目: 日付／居住地／年代／性別
・出展: 山梨県ウェブサイト（リンク: https://www.pref.yamanashi.jp/koucho/coronavirus/info_coronavirus.html）

県内の疑似症例の検査状況
・合計人数
・棒グラフ（2/1〜本日までの日割り）
・出展: 山梨県ウェブサイト（リンク: https://www.pref.yamanashi.jp/koucho/coronavirus/info_coronavirus.html）

**Comment by keitasuzukijp** [comment]
参考：各県サイトの掲載グラフ

▼東京都
https://stopcovid19.metro.tokyo.lg.jp/
検査陽性者の状況
陽性患者数
陽性患者の属性
検査実施数
新型コロナコールセンター相談件数
新型コロナ受診相談窓口相談件数

▼北海道
https://stopcovid19.hokkaido.dev/
現在患者数
陰性確認数
陽性患者数
陽性患者の属性
新型コロナコールセンター相談件数(札幌市保健所値)
帰国者・接触者電話相談センター相談件数(札幌市保健所値)

▼神奈川県
https://www.pref.kanagawa.jp/osirase/1369/
陽性患者数
陽性患者の属性
コロナウイルス感染症専用ダイヤル相談件数
帰国者・接触者電話相談センター相談件数
LINE公式アカウント「新型コロナ対策パーソナルサポート（行政）」友だち数

**Comment by keitasuzukijp** [comment]
@yuukis 
グラフ用のデータです。
https://docs.google.com/spreadsheets/d/1CQpkwcMZRJHD27wTESbnP0Yj1WxwUMnUOW-EF0XvkAw/edit?usp=sharing

**Comment by keitasuzukijp** [comment]
期待される表示：
・現状公開されている下記の3データのみにする。
　・陽性患者数
　・陽性患者の属性
　・県内の疑似症例の検査状況
・それ以外のグラフは非表示とする。

**Comment by yuukis** [comment]
とりあえず今こんな感じです。

　・陽性患者数
　・陽性患者の属性
　・県内の疑似症例の検査状況
の3つだけ残してます。

![FireShot Capture 015 - 都内の最新感染動向 - 東京都 新型コロナウイルス感染症対策サイト - localhost](https://user-images.githubusercontent.com/2931035/76591654-56f7b300-6534-11ea-92a8-ac7b09f6fcdf.png)

**Comment by keitasuzukijp** [comment]
@yuukis 
ありがとうございます！
データの更新とともにステージングによろしくお願いいたします。

**Comment by keitasuzukijp** [comment]
@yuukis 
グラフ下の「オープンデータへのリンク」と箇所も上記「出展: 山梨県ウェブサイト」に変更ください。
