### ISSUE TITLE
テーマカラー設定

### ISSUE THREAD

**Issue by keitasuzukijp** [covid19-yamanashi/covid19#7]
グラフなどで使う色を決める。
山梨県の紫色？

**Comment by keitasuzukijp** [comment]
#694e84 ←棒グラフの色？
#cbbbdf
#ede9f7

**Comment by keitasuzukijp** [comment]
MetroBarChart.vue
にのみ反映済み

**Comment by keitasuzukijp** [comment]
MetroBarChart.vue以外にも反映したいです。
・ローディング中のバー
・サイドメニューの現在地表示

**Comment by liencode** [comment]
@keitasuzukijp これどの色反映すればいいですか？

**Comment by keitasuzukijp** [comment]
@liencode 
#694e84 で！

**Comment by 38tk** [comment]
@liencode @keitasuzukijp サイドメニューの配色だけ変えてみました。

**Comment by keitasuzukijp** [comment]
@38tk @liencode 
ありがとうございます！
ローディングのバーの色をどこで変えればいいのか…（汗）

**Comment by liencode** [comment]
昨日夜予定あって作業できなかった..ありがとうございます！
