### ISSUE TITLE
Forkボタンを押すと東京都のリポジトリに移動する。

### ISSUE THREAD

**Issue by Tree-frog-code** [covid19-yamanashi/covid19#73]
こんにちは。このリポジトリをforkしようとgithubのforkボタンを押したのですが、東京都のリポジトリに移動してしまいます。
山梨県版のリポジトリをクローンして新しく作ったリポジトリにpushすれば良いですか?
もし他に良い方法や正しい方法があれば教えていただけないでしょうか。

**Comment by shikachii** [comment]
リポジトリを確認させていただいたところ3月20日付近の東京都covid19リポジトリがフォークされているようです。
GitHub上の同じアカウント内に同じ名前のリポジトリは1つまでしか作成できないので山梨県covid19リポジトリが作成できないものと見られます。
東京都のリポジトリに何かしら手を加える予定が無いのであればフォークした東京都のリポジトリを消してから山梨県のリポジトリをフォークしていただければ作成できるかと思います。

**Comment by Tree-frog-code** [comment]
わかりました。同じリポジトリを２つ作成できないということを知らなかったので、とても参考になりました。
コメントの通りにやってみます。

**Comment by Tree-frog-code** [comment]
無事forkすることができました。ありがとうございました。
またこのようなことがあった時も教えていただけるとありがたいです。

**Comment by shikachii** [comment]
お役に立てたようでなによりです :smile:
