### ISSUE TITLE
「陽性患者の属性」のリリース日の扱いについて

### ISSUE THREAD

**Issue by daisuke19891023** [covid19-yamanashi/covid19#80]
## 起こっている問題 / The Problem
山梨県の患者情報の掲載ページの表示方法の変更に伴い、最新の患者情報について「リリース日」
の情報が表示されなくなった。

- [60件目まで](https://www.pref.yamanashi.jp/koucho/coronavirus/info_coronavirus_past.html)は従来通りPDF表記（リリース日に相当する情報がある）
- [61件目以降](https://www.pref.yamanashi.jp/koucho/coronavirus/info_coronavirus_prevention.html)はhtmlに直接表示（リリース日に相当する情報がない）

`data.json`の患者毎の日付情報としては「リリース日」を属性として持たせているため、61件目以降の患者情報としてそれに相当する情報が取得できなくなっている。

## スクリーンショット / Screenshot

従来のPDF形式の患者情報から情報を取得する場合、リリース日はPDFファイルのファイル名に記載された日付を取得していた
![image](https://user-images.githubusercontent.com/29330441/84586372-0a35b800-ae54-11ea-91f9-1d52fcf26102.png)

現在の61件目以降の表示。発生判明日は表示されるが、リリース日に相当する日付は存在しない。
![image](https://user-images.githubusercontent.com/29330441/84586317-6b10c080-ae53-11ea-8e87-ccf173da9c02.png)

## 期待する見せ方・挙動 / Expected Behavior
新規の表示形式に対応する形で現在スクレイピングを修正している。
`data.json`に格納するデータに関し、以下のどちらかの仕様に合わせる形で修正する必要がある。
- 案1:61件目以降のデータに関し、「発生判明日」と同一の日時を「リリース日」として設定する
- 案2:すべての患者情報に対して「リリース日」ではなく、「発生判明日」を日付情報として採用する（この場合、Vue側でも修正が必要）

**Comment by yuukis** [comment]
@daisuke19891023 
起票ありがとうございます！

> 案2:すべての患者情報に対して「リリース日」ではなく、「発生判明日」を日付情報として採用する（この場合、Vue側でも修正が必要）

「Vue側でも修正が必要」というのは、
`data.json` の患者属性にある `リリース日` というキー名自体が `発生判明日` に変わる
ということでしょうか。
であれば、Vue側は「リリース日」を「発生判明日」に置換する修正になる想定です。

個人的にはリリース日よりも発生判明日を表示させた方が、陽性患者数グラフの日付と合うので良いと思っています。（＝案1よりも案2が良い）
→ @keitasuzukijp さん、認識合いますか？

**Comment by daisuke19891023** [comment]
> 「Vue側でも修正が必要」というのは、
data.json の患者属性にある リリース日 というキー名自体が 発生判明日 に変わる
ということでしょうか。
であれば、Vue側は「リリース日」を「発生判明日」に置換する修正になる想定です

はい、ご認識の通りです。
キー名を「リリース日」にしてしまえばVue側の修正は不要となりますが、
後々のことを考えるとキー名を「発生判明日」とした方がメンテナンスがやりやすいと思います。

**Comment by yuukis** [comment]
@daisuke19891023 
> キー名を「リリース日」にしてしまえばVue側の修正は不要となりますが、
> 後々のことを考えるとキー名を「発生判明日」とした方がメンテナンスがやりやすいと思います。

→ありがとうございます。理解しました。

では【案2】でお願いします！
Vue側の修正は並行してこちらで進めておきます。

**Comment by daisuke19891023** [comment]
`data.json`はマージされているみたいなので、確認済みだとは思いますが、
スクレイピングツールの方は本日修正完了しました。

**Comment by yuukis** [comment]
> `data.json`はマージされているみたいなので、確認済みだとは思いますが、
> スクレイピングツールの方は本日修正完了しました。

確認しました
ご対応ありがとうございました！！

Vue側の修正も完了してマージ済み(#81) のため、クローズします。
