### ISSUE TITLE
TOP: 「自分や家族の症状に不安や心配があればまずは電話相談をどうぞ」欄を消す

### ISSUE THREAD

**Issue by keitasuzukijp** [covid19-yamanashi/covid19#9]
https://stopcovid19-dev.yamanashi.dev/
StaticInfoのところ

**Comment by yuukis** [comment]
やります！

**Comment by yuukis** [comment]
@keitasuzukijp 
flow ページも消します？
https://stopcovid19-dev.yamanashi.dev/flow
